-- Typed models for the Typebot SDK (LuaLS annotations).
--
-- GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
-- params (op.<name>.points[].args.params[]). Field/param types come from the
-- canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
-- @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
-- edit by hand.

---@class Analytics
---@field totalCompleted number
---@field totalStarts number
---@field totalViews number

---@class AnalyticsLoadMatch
---@field typebot_id string
---@field time_filter? string
---@field time_zone? string

---@class Billing
---@field amount number
---@field currency string
---@field date any
---@field id string
---@field resetsAt string
---@field totalChatsUsed number
---@field url string

---@class BillingLoadMatch
---@field workspace_id string

---@class BillingListMatch
---@field workspace_id string

---@class Folder
---@field createdAt string
---@field folder table
---@field folderName? string
---@field id string
---@field name string
---@field parentFolderId any
---@field updatedAt string
---@field workspaceId string

---@class FolderLoadMatch
---@field id string
---@field workspace_id string

---@class FolderListMatch
---@field parent_folder_id? string
---@field workspace_id string

---@class FolderCreateData
---@field createdAt string
---@field folder table
---@field folderName? string
---@field id string
---@field name string
---@field parentFolderId any
---@field updatedAt string
---@field workspaceId string

---@class FolderUpdateData
---@field id string
---@field createdAt? string
---@field folder? table
---@field folderName? string
---@field name? string
---@field parentFolderId? any
---@field updatedAt? string
---@field workspaceId? string

---@class FolderRemoveMatch
---@field id string

---@class Result
---@field answers table
---@field context any
---@field createdAt string
---@field description string
---@field details any
---@field hasStarted any
---@field id string
---@field isArchived any
---@field isCompleted boolean
---@field lastChatSessionId any
---@field resultId string
---@field status string
---@field typebotId string
---@field variables table

---@class ResultLoadMatch
---@field id string
---@field typebot_id string

---@class ResultListMatch
---@field typebot_id string
---@field cursor? number
---@field limit? number
---@field time_filter? string
---@field time_zone? string

---@class ResultRemoveMatch
---@field typebot_id string

---@class Typebot
---@field accessRight string
---@field createdAt string
---@field customDomain any
---@field edges table
---@field enableSafetyFlags? boolean
---@field events table
---@field folderId any
---@field fromTemplate? string
---@field groups table
---@field icon any
---@field id string
---@field isArchived boolean
---@field isClosed boolean
---@field message any
---@field name string
---@field overwrite? boolean
---@field publicId any
---@field publishedTypebot any
---@field publishedTypebotId? string
---@field resultsTablePreferences any
---@field riskLevel any
---@field selectedThemeTemplateId any
---@field settings table
---@field spaceId any
---@field theme table
---@field typebot table
---@field updatedAt string
---@field variables table
---@field version? any
---@field warnings? table
---@field whatsAppCredentialsId any
---@field workspaceId string

---@class TypebotLoadMatch
---@field id string
---@field migrate_to_latest_version? boolean

---@class TypebotListMatch
---@field folder_id? string
---@field workspace_id string

---@class TypebotCreateData
---@field accessRight string
---@field createdAt string
---@field customDomain any
---@field edges table
---@field enableSafetyFlags? boolean
---@field events table
---@field folderId any
---@field fromTemplate? string
---@field groups table
---@field icon any
---@field id string
---@field isArchived boolean
---@field isClosed boolean
---@field message any
---@field name string
---@field overwrite? boolean
---@field publicId any
---@field publishedTypebot any
---@field publishedTypebotId? string
---@field resultsTablePreferences any
---@field riskLevel any
---@field selectedThemeTemplateId any
---@field settings table
---@field spaceId any
---@field theme table
---@field typebot table
---@field updatedAt string
---@field variables table
---@field version? any
---@field warnings? table
---@field whatsAppCredentialsId any
---@field workspaceId string

---@class TypebotUpdateData
---@field id string
---@field accessRight? string
---@field createdAt? string
---@field customDomain? any
---@field edges? table
---@field enableSafetyFlags? boolean
---@field events? table
---@field folderId? any
---@field fromTemplate? string
---@field groups? table
---@field icon? any
---@field isArchived? boolean
---@field isClosed? boolean
---@field message? any
---@field name? string
---@field overwrite? boolean
---@field publicId? any
---@field publishedTypebot? any
---@field publishedTypebotId? string
---@field resultsTablePreferences? any
---@field riskLevel? any
---@field selectedThemeTemplateId? any
---@field settings? table
---@field spaceId? any
---@field theme? table
---@field typebot? table
---@field updatedAt? string
---@field variables? table
---@field version? any
---@field warnings? table
---@field whatsAppCredentialsId? any
---@field workspaceId? string

---@class TypebotRemoveMatch
---@field id string

---@class Workspace
---@field chatsHardLimit any
---@field createdAt string
---@field customChatsLimit any
---@field customSeatsLimit any
---@field icon any
---@field id string
---@field inactiveFirstEmailSentAt any
---@field inactiveSecondEmailSentAt any
---@field isPastDue boolean
---@field isSuspended boolean
---@field isVerified any
---@field lastActivityAt any
---@field name string
---@field plan string
---@field role string
---@field settings any
---@field stripeId any
---@field updatedAt string
---@field user table
---@field userId string
---@field workspaceId string

---@class WorkspaceLoadMatch
---@field id string

---@class WorkspaceListMatch
---@field chatsHardLimit? any
---@field createdAt? string
---@field customChatsLimit? any
---@field customSeatsLimit? any
---@field icon? any
---@field id? string
---@field inactiveFirstEmailSentAt? any
---@field inactiveSecondEmailSentAt? any
---@field isPastDue? boolean
---@field isSuspended? boolean
---@field isVerified? any
---@field lastActivityAt? any
---@field name? string
---@field plan? string
---@field role? string
---@field settings? any
---@field stripeId? any
---@field updatedAt? string
---@field user? table
---@field userId? string
---@field workspaceId? string

---@class WorkspaceCreateData
---@field chatsHardLimit any
---@field createdAt string
---@field customChatsLimit any
---@field customSeatsLimit any
---@field icon any
---@field id string
---@field inactiveFirstEmailSentAt any
---@field inactiveSecondEmailSentAt any
---@field isPastDue boolean
---@field isSuspended boolean
---@field isVerified any
---@field lastActivityAt any
---@field name string
---@field plan string
---@field role string
---@field settings any
---@field stripeId any
---@field updatedAt string
---@field user table
---@field userId string
---@field workspaceId string

---@class WorkspaceUpdateData
---@field id string
---@field chatsHardLimit? any
---@field createdAt? string
---@field customChatsLimit? any
---@field customSeatsLimit? any
---@field icon? any
---@field inactiveFirstEmailSentAt? any
---@field inactiveSecondEmailSentAt? any
---@field isPastDue? boolean
---@field isSuspended? boolean
---@field isVerified? any
---@field lastActivityAt? any
---@field name? string
---@field plan? string
---@field role? string
---@field settings? any
---@field stripeId? any
---@field updatedAt? string
---@field user? table
---@field userId? string
---@field workspaceId? string

---@class WorkspaceRemoveMatch
---@field id string

local M = {}

return M
